# Generated by Django 6.0.4 on 2026-04-12 00:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de cuenta', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de cuenta', null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del cliente')),
                ('activo', models.BooleanField(default=True, help_text='Estado del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['email'], name='gestion_cli_email_7bb1dd_idx'), models.Index(fields=['nombre'], name='gestion_cli_nombre_e5285d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(help_text='Número único de cuenta', max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual de la cuenta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, help_text='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha de cierre (si aplica)', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Estado de la cuenta')),
                ('cliente', models.ForeignKey(help_text='Cliente propietario de la cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente')),
                ('tipo_cuenta', models.ForeignKey(blank=True, help_text='Tipo de cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tipocuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-fecha_apertura'],
                'unique_together': {('cliente', 'numero_cuenta')},
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transacciones', models.IntegerField(default=0, help_text='Total de transacciones')),
                ('monto_total_enviado', models.DecimalField(decimal_places=2, default=0, help_text='Monto total enviado', max_digits=12)),
                ('monto_total_recibido', models.DecimalField(decimal_places=2, default=0, help_text='Monto total recibido', max_digits=12)),
                ('fecha_generacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del reporte')),
                ('cuenta', models.OneToOneField(help_text='Cuenta asociada al reporte', on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='gestion.cuenta')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO', 'Pago')], help_text='Tipo de transacción', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual de la transacción', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la transacción', null=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la transacción')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha de procesamiento', null=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, help_text='Cuenta de destino (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_recibidas', to='gestion.cuenta')),
                ('cuenta_origen', models.ForeignKey(help_text='Cuenta de origen', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to='gestion.cuenta')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_transaccion'],
                'indexes': [models.Index(fields=['cuenta_origen', 'fecha_transaccion'], name='gestion_tra_cuenta__4bc9af_idx'), models.Index(fields=['estado'], name='gestion_tra_estado_51c03a_idx'), models.Index(fields=['tipo'], name='gestion_tra_tipo_24c896_idx')],
            },
        ),
    ]
